/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EggAbi } from "./EggAbi";
export * as factories from "./factories";
export { EggAbi__factory } from "./factories/EggAbi__factory";
